// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gomigrate
{
    [GomigrateResourceType("gomigrate:index:Migration")]
    public partial class Migration : Pulumi.CustomResource
    {
        /// <summary>
        /// Date of the migration
        /// </summary>
        [Output("migratedAt")]
        public Output<string> MigratedAt { get; private set; } = null!;


        /// <summary>
        /// Create a Migration resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Migration(string name, MigrationArgs args, CustomResourceOptions? options = null)
            : base("gomigrate:index:Migration", name, args ?? new MigrationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Migration(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("gomigrate:index:Migration", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/LuxChanLu",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Migration resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Migration Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Migration(name, id, options);
        }
    }

    public sealed class MigrationArgs : Pulumi.ResourceArgs
    {
        [Input("databaseURL", required: true)]
        private Input<string>? _databaseURL;

        /// <summary>
        /// Database URL to run the migrations on
        /// </summary>
        public Input<string>? DatabaseURL
        {
            get => _databaseURL;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _databaseURL = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Previous version to migrate on undo
        /// </summary>
        [Input("prevVersion", required: true)]
        public Input<int> PrevVersion { get; set; } = null!;

        [Input("sourceURL", required: true)]
        private Input<string>? _sourceURL;

        /// <summary>
        /// Source URL for the migrations
        /// </summary>
        public Input<string>? SourceURL
        {
            get => _sourceURL;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _sourceURL = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Version to migrate
        /// </summary>
        [Input("version", required: true)]
        public Input<int> Version { get; set; } = null!;

        public MigrationArgs()
        {
        }
    }
}
